services:
  - type: web
    name: tableau-data-reporter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run tableau_streamlit_app.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true 