services:
  - type: web
    name: tableau-data-reporter
    env: python
    plan: free
    buildCommand: |
      chmod +x start.sh
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true 