services:
  - type: web
    name: tableau-data-reporter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8501
    autoDeploy: true 